# Cloudflare Pages + KV workspace
# Namespace: WORKSPACE_KV

name = "trading-terminal"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "WORKSPACE_KV"
id = "cb0bf5a156e541f3a771578c0c117678"
