export { DeepDomOverlay } from './DeepDomOverlay'
export { DomLadder } from './DomLadder'
export { detectFlashLevels } from './bookSurprise'
export type { FlashEvent, FlashKind } from './bookSurprise'
export type { DeepDomConfig, DomSnapshot, DomLevel, DomSurprise } from './types'
export { DEFAULT_DEEP_DOM_CONFIG, L2_GRANULARITY_NOTES } from './types'
